#!/bin/bash
# Auto-bump versão em index.html a cada commit

TODAY=$(date +%Y.%m.%d)
CURRENT=$(grep -o "v[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}[a-z]\+" /home/user/appDamata/index.html | head -1)
CURRENT_DATE=$(echo "$CURRENT" | grep -o '[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}')
CURRENT_SUFFIX=$(echo "$CURRENT" | sed 's/v[0-9]*\.[0-9]*\.[0-9]*//')

if [ "$CURRENT_DATE" = "$TODAY" ]; then
  NEXT_SUFFIX=$(python3 -c "
s='${CURRENT_SUFFIX}'
def inc(s):
    if not s: return 'a'
    if s[-1] < 'z': return s[:-1] + chr(ord(s[-1])+1)
    return inc(s[:-1]) + 'a'
print(inc(s))
")
  NEW_VER="v${TODAY}${NEXT_SUFFIX}"
else
  NEW_VER="v${TODAY}a"
fi

if [ "$CURRENT" != "$NEW_VER" ]; then
  sed -i "s/${CURRENT}/${NEW_VER}/g" /home/user/appDamata/index.html
  git add /home/user/appDamata/index.html
  echo "🔖 Versão atualizada: $CURRENT → $NEW_VER"
fi
